---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphhopper
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: graphhopper
        image: ghcr.io/bikehopper/graphhopper:v4.0-beta7
        envFrom:
        - secretRef:
            name: minio-creds
        env:
        - name: BUCKET_NAME
          value: graphhopper-staging

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: graphhopper-graph-cache-builder
spec:
  schedule: "0 8,20 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: graphhopper-graph-cache-builder
            image: ghcr.io/bikehopper/graphhopper-graph-cache-builder:v4.0-beta7
            envFrom:
            - secretRef:
                name: minio-creds
            - secretRef:
                name: api-511
            env:
            - name: BUCKET_NAME
              value: graphhopper-staging
