graphhopper:
#  datareader.file: germany-latest.osm.pbf
#  graph.location: graphs/germany/graph

  datareader.file: sachsen-latest.osm.pbf
  graph.location: graphs/sachsen/graph

  profiles:
    - name: car
      vehicle: car
      weighting: time_dependent_restrictions

  profiles_lm:
    - profile: car

  graph.flag_encoders: car
  prepare.lm.landmarks: 8

server:
  application_connectors:
  - type: http
    port: 8989
  admin_connectors:
  - type: http
    port: 8990

viewRendererConfiguration:
  freemarker:
    objectWrapper: DefaultObjectWrapper(2.3.28, exposeFields=true, iterableSupport=true)
