graphhopper:
  datareader.file: brandenburg-latest.osm.pbf
  # for multiple files you can use: gtfs.file: file1.zip,file2.zip,file3.zip
  gtfs.file: gtfs-vbb.zip
  graph.location: graphs/brandenburg-with-transit

  profiles:
    - name: foot
      custom_model_files:
        - foot.json
      # optionally add
      #  - foot_elevation.json

  import.osm.ignored_highways: motorway,trunk
  graph.encoded_values: foot_access, foot_average_speed, hike_rating, foot_priority

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
