---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphhopper
  labels:
    app: graphhopper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphhopper
  template:
    metadata:
      labels:
        app: graphhopper
    spec:
      containers:
      - name: graphhopper
        ports:
          - containerPort: 8989
          - name: health-port
            containerPort: 8989
        resources:
          requests:
            memory: "6Gi"
            cpu: "3000m"
          limits:
            memory: "12Gi"
            cpu: "8000m"
        env:
        - name: JVM_ARGS
          value: -Xms5g -Xmx10g
        - name: GEOFABRIK_PATH
          value: /north-america/us/california/norcal-latest.osm.pbf
        - name: OSM_PBF_FILE_NAME
          value: current-norcal-latest.osm.pbf
        - name: API_511_PATH
          value: /transit/datafeeds?api_key=02a6fde6-e10a-49ce-a96e-5ad9404f137f&operator_id=RG
        - name: API_511_FILE_NAME
          value: current-GTFSTransitData_RG.zip
        - name: MINIO_HOST
          value: http://minio.techlabor.org:9000
        readinessProbe:
          httpGet:
            path: /health
            port: health-port
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /health
            port: health-port
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 20
---
apiVersion: v1
kind: Service
metadata:
  name: graphhopper-svc
  labels:
    run: graphhopper
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8989
    protocol: TCP
    name: http
  selector:
    app: graphhopper
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: graphhopper-graph-cache-builder
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: graphhopper-graph-cache-builder
            resources:
              requests:
                memory: "16Gi"
                cpu: "6000m"
            envFrom:
            - secretRef:
                name: api-511
            env:
            - name: GEOFABRIK_PATH
              value: /north-america/us/california/norcal-latest.osm.pbf
            - name: OSM_PBF_FILE_NAME
              value: current-norcal-latest.osm.pbf
            - name: API_511_PATH
              value: /transit/datafeeds?operator_id=RG
            - name: API_511_FILE_NAME
              value: current-GTFSTransitData_RG.zip
            - name: MINIO_HOST
              value: http://minio.techlabor.org:9000
          imagePullSecrets:
          - name: dockerconfigjson-github-com
          restartPolicy: Never
