name: Trigger Benchmarks
on: push
jobs:
  trigger_measurement:
    if: github.repository_owner == 'Apaq'
    runs-on: ubuntu-22.04
    environment: benchmarks
    steps:
      - name: trigger
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.BENCHMARKS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ secrets.BENCHMARKS_REPO }}/dispatches" \
          -d '{"event_type":"measurement_core","client_payload":{"core_commit": "'$GITHUB_SHA'", "core_branch": "${{ github.ref_name }}" }}'
